MyFund/Controllers/BackingPackagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.SignalR;
using Microsoft.EntityFrameworkCore;
using MyFund.Extensions;
using MyFund.DataModel;
using MyFund.Services;
using MyFund.Authorization;

namespace MyFund.Controllers
{
    [Authorize]
    public class BackingPackagesController : Controller
    {
        private readonly CrowdContext _context;

        public BackingPackagesController(CrowdContext context)
        {
            _context = context;
        }

        // GET: BackingPackages
        [AllowAnonymous]
        public async Task<IActionResult> Index(long? projectId)
        {
            if (projectId.HasValue)
            {
                var projectContext = await _context.Project
                                            .Include(p => p.BackingPackages)
                                            .FirstOrDefaultAsync(p => p.Id == projectId);
                if (projectContext==null)
                {
                    return NotFound();
                }

                if (User.Identity.IsAuthenticated)
                {
                    var userBackingQuery = from ub in _context.UserBacking
                                           join bp in projectContext.BackingPackages on ub.BackingId equals bp.Id
                                           where ub.UserId == User.GetUserId()
                                           select ub;

                    await userBackingQuery.LoadAsync();

                    if (userBackingQuery.Count() == 1)
                    {
                        var userBacking = userBackingQuery.Single();
                        projectContext.BackingPackages.First(bp => bp.Id == userBacking.BackingId).UserBackings.Add(userBacking);
                    }
                }

                return View(projectContext.BackingPackages.OrderBy(bp => bp.BackingAmount));
            }

            return NotFound();
        }

        // GET: BackingPackages/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var backingPackage = await _context.BackingPackage
                .Include(b => b.AttatchmentSet)
                .Include(b => b.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
       
            if (backingPackage == null)
            {
                return NotFound();
            }

            if (User.Identity.IsAuthenticated && backingPackage.Project.UserId != User.GetUserId())
            {
                var userBacking = await _context.UserBacking.SingleOrDefaultAsync(ub => ub.BackingId == backingPackage.Id && ub.UserId == User.GetUserId());
                backingPackage.UserBackings.Add(userBacking);
            }

            return View(backingPackage);
        }

        // GET: BackingPackages/Create/4
        [AuthorizeResource(typeof(ResourceOwnerRequirement), typeof(Project))]
        public async Task<IActionResult> Create(long projectId)
        {
            if (projectId > 0)
            {
                var projectContext = await _context.Project.FindAsync(projectId);
                if (projectContext == null)
                {
                    return NotFound();
                }

                ViewData["ProjectId"] = projectId;
                return View();
            }
            else
            {
                return NotFound();
            }
        }

        // POST: BackingPackages/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("BackingPackages/Create")]
        [ValidateAntiForgeryToken]
        [AuthorizeResource(typeof(ResourceOwnerRequirement), typeof(Project))]
        public async Task<IActionResult> Create(long projectId, [Bind("Id,Name,PackageDescription,BackingAmount,RewardDescription,DateCreated,DateUpdated,ProjectId,AttatchmentSetId")] BackingPackage backingPackage)
        {
            if (ModelState.IsValid)
            {
                backingPackage.DateCreated = DateTime.Now;
                _context.Add(backingPackage);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ProjectsController.Details), "Projects", new { Id = backingPackage.ProjectId });
            }
            return View(backingPackage);
        }

        // GET: BackingPackages/Edit/5
        [AuthorizeResource(typeof(ResourceOwnerRequirement), typeof(BackingPackage), "Project")]
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var backingPackage = await _context.BackingPackage.FindAsync(id);
            if (backingPackage == null)
            {
                return NotFound();
            }
            ViewData["AttatchmentSetId"] = new SelectList(_context.AttatchmentSet, "Id", "Id", backingPackage.AttatchmentSetId);
            ViewData["ProjectId"] = new SelectList(_context.Project, "Id", "Name", backingPackage.ProjectId);
            return View(backingPackage);
        }

        // POST: BackingPackages/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AuthorizeResource(typeof(ResourceOwnerRequirement), typeof(BackingPackage), "Project")]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,PackageDescription,BackingAmount,RewardDescription,DateCreated,DateUpdated,ProjectId,AttatchmentSetId")] BackingPackage backingPackage)
        {
            if (id != backingPackage.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(backingPackage);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BackingPackageExists(backingPackage.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AttatchmentSetId"] = new SelectList(_context.AttatchmentSet, "Id", "Id", backingPackage.AttatchmentSetId);
            ViewData["ProjectId"] = new SelectList(_context.Project, "Id", "Name", backingPackage.ProjectId);
            return View(backingPackage);
        }

        // GET: BackingPackages/Delete/5
        [AuthorizeResource(typeof(ResourceOwnerRequirement), typeof(BackingPackage), "Project")]
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var backingPackage = await _context.BackingPackage
                .Include(b => b.AttatchmentSet)
                .Include(b => b.Project)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (backingPackage == null)
            {
                return NotFound();
            }

            return View(backingPackage);
        }

        // POST: BackingPackages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [AuthorizeResource(typeof(ResourceOwnerRequirement), typeof(BackingPackage), "Project")]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var backingPackage = await _context.BackingPackage.FindAsync(id);
            _context.BackingPackage.Remove(backingPackage);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BackingPackageExists(long id)
        {
            return _context.BackingPackage.Any(e => e.Id == id);
        }
    }
}

MyFund/Views/BackingPackages/Create.cshtml
@model BackingPackage

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>BackingPackage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-route-projectId="@ViewData["ProjectId"]">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PackageDescription" class="control-label"></label>
                <input asp-for="PackageDescription" class="form-control" />
                <span asp-validation-for="PackageDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BackingAmount" class="control-label"></label>
                <input asp-for="BackingAmount" class="form-control" />
                <span asp-validation-for="BackingAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RewardDescription" class="control-label"></label>
                <input asp-for="RewardDescription" class="form-control" />
                <span asp-validation-for="RewardDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Projects" asp-action="Details" asp-route-id="ProjectId">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyFund/Views/BackingPackages/Delete.cshtml
@model BackingPackage

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BackingPackage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PackageDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PackageDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BackingAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BackingAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RewardDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RewardDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AttatchmentSet)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AttatchmentSet.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyFund/Views/BackingPackages/Details.cshtml
@model BackingPackage

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>BackingPackage</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PackageDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PackageDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BackingAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BackingAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RewardDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RewardDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AttatchmentSet)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AttatchmentSet.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Project)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Project.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyFund/Views/BackingPackages/Edit.cshtml
@model BackingPackage

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>BackingPackage</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PackageDescription" class="control-label"></label>
                <input asp-for="PackageDescription" class="form-control" />
                <span asp-validation-for="PackageDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BackingAmount" class="control-label"></label>
                <input asp-for="BackingAmount" class="form-control" />
                <span asp-validation-for="BackingAmount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RewardDescription" class="control-label"></label>
                <input asp-for="RewardDescription" class="form-control" />
                <span asp-validation-for="RewardDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateUpdated" class="control-label"></label>
                <input asp-for="DateUpdated" class="form-control" />
                <span asp-validation-for="DateUpdated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.ProjectId"></select>
                <span asp-validation-for="ProjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AttatchmentSetId" class="control-label"></label>
                <select asp-for="AttatchmentSetId" class="form-control" asp-items="ViewBag.AttatchmentSetId"></select>
                <span asp-validation-for="AttatchmentSetId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyFund/Views/BackingPackages/Index.cshtml
@model IEnumerable<BackingPackage>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PackageDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BackingAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RewardDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateUpdated)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AttatchmentSet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Project)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PackageDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BackingAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RewardDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateUpdated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AttatchmentSet.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MyFund/Views/BackingPackages/_DetailsPartial.cshtml
@model BackingPackage

<div class="@(Model.UserBackings.Any() ? "text-primary bg-primary" : "")">
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PackageDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PackageDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BackingAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BackingAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RewardDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RewardDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateUpdated)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateUpdated)
        </dd>
    </dl>
</div>
<div>

</div>

MyFund/Views/BackingPackages/_IndexPartial.cshtml
@model Project

<h4>Pledge tiers</h4>
@{
    var authorizationResult = (await AuthorizationService.AuthorizeAsync(User, Model, "ProjectCreator"));
    if (authorizationResult.Succeeded)
    {
        <p>
            <a asp-controller="BackingPackages" asp-action="Create" asp-route-projectId="@Model.Id">Create new package</a>
        </p>
    }
    else
    {
        <p></p>
    }
}
<table class="table">
    <tbody>
        @foreach (var item in Model.BackingPackages)
        {
            <tr>
                <td class="td-backing-item-view">
                    <div>
                        @await Html.PartialAsync("_DetailsPartial.cshtml", item)
                    </div>
                </td>
            </tr>
            <tr>
                <td class="td-backing-item-nav">
                    @if ((await AuthorizationService.AuthorizeAsync(User, Model, "ProjectCreator")).Succeeded)
                    {
                        <a asp-controller="BackingPackages" asp-action="Edit" asp-route-id="@item.Id">Edit</a><span> | </span>
                    }
                    <a asp-controller="BackingPackages" asp-action="Details" asp-route-id="@item.Id">Details</a>
                    @if ((await AuthorizationService.AuthorizeAsync(User, Model, "ProjectCreator")).Succeeded)
                    {
                        <span> | </span><a asp-controller="BackingPackages" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>